# Generated by Django 4.2.3 on 2024-02-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0002_chatlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='chatlognr',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
